### ISSUE TITLE
TLS secret doesn't replicate crt and key

### ISSUE THREAD

**Issue by khos2ow** [mittwald/kubernetes-replicator#23]
I'm trying to replicate `Secret` of type `kubernetes.io/tls` from namespace `from-namespace` to `to-namespace` and the replication doesn't work. This is pretty similar to #7 and #11, but neither of solutions seem to be working on my side.

The original secret to copy:
```yaml
apiVersion: v1
data:
  ca.crt: ""
  tls.crt: <omitted>
  tls.key: <omitted>
kind: Secret
metadata:
  annotations:
    ...
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: .*
  name: from-cert
  namespace: from-namespace
type: kubernetes.io/tls
```

to the target secret:
```yaml
apiVersion: v1
type: kubernetes.io/tls
kind: Secret
metadata:
  name: to-cert
  labels:
  annotations:
    replicator.v1.mittwald.de/replication-from: from-namespace/from-cert
data: {}
```

when `kubectl apply` the above I'm getting this error:
```
The Secret "to-cert" is invalid:
* data[tls.crt]: Required value
* data[tls.key]: Required value
```

which was suggested https://github.com/mittwald/kubernetes-replicator/issues/11#issuecomment-512246509 and with applying the following

```yaml
apiVersion: v1
type: kubernetes.io/tls
kind: Secret
metadata:
  name: to-cert
  labels:
  annotations:
    replicator.v1.mittwald.de/replication-from: from-namespace/from-cert
data:
  tls.crt: ""
  tls.key: ""
```

The `tls.crt` and `tls.key` are not copied over based on values from `from-namespace/from-cert` and there's no log in `replicator-deployment`. I've tried both `master` and `v2.0.1` deployment in `kube-system`. Am I missing something here? Any idea/suggestions?

**Comment by khos2ow** [comment]
Oh my god! I have a typo!! it shouldn't be `replicator.v1.mittwald.de/**replication**-from`. For future reference this worked for me:

```yaml
apiVersion: v1
data:
  ca.crt: ""
  tls.crt: <omitted>
  tls.key: <omitted>
kind: Secret
metadata:
  annotations:
    ...
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: .*
  name: from-cert
  namespace: from-namespace
type: kubernetes.io/tls
```
and
```yaml
apiVersion: v1
type: kubernetes.io/tls
kind: Secret
metadata:
  name: to-cert
  labels:
  annotations:
    replicator.v1.mittwald.de/replicate-from: from-namespace/from-cert
data:
  tls.crt: ""
  tls.key: ""
```
