### ISSUE TITLE
Not replicating .dockerconfigjson registry secrets

### ISSUE THREAD

**Issue by cabrinha** [mittwald/kubernetes-replicator#28]
Simple and common use case: Replicate the registry credentials to all namespaces.

Typically this is a secret named "regcred" and it's data field is:

```
data:
  .dockerconfigjson: <base64 auth string here>
```

Seems that kubernetes-replicator does not copy these over.

**Comment by MarkusH** [comment]
I can confirm an unexpected behavior.

We have a `templates` namespace with some ConfigMaps and Secrets. The `templates/image-pull` secret looks like this:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: image-pull
  namespace: templates
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "some-namespace,others-[a-f0-9]{16}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64 encoded secret>
```

In the namespaces `some-namespace` and `others-[a-f0-9]{16}` we have an `image-pull` secret as well, created as this:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: image-pull
  namespace: some-namespace
  annotations:
    replicator.v1.mittwald.de/replicate-from: templates/image-pull
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K  # this is `{}` base64 encoded
```

We can't seem to create the `some-namespace/image-pull` secret with an empty `data` key, as Kubernetes won't allow that for secrets of type `kubernetes.io/dockerconfigjson`.

We're currently running v1.0.0 (`quay.io/mittwald/kubernetes-replicator:v1.0.0`) since none of the changes in 2.0.0 or 2.0.1 seemed relevant and we don't use binary data in config maps.
