### ISSUE TITLE
Fails to replicate `secret` despite correct configuration

### ISSUE THREAD

**Issue by lrdplopes** [mittwald/kubernetes-replicator#358]
**Describe the bug**
We are experiencing an issue where `kubernetes-replicator` does not replicate a `secret` to a target namespace, even though the configuration appears correct.

**To Reproduce**
```
apiVersion: v1
kind: Secret
metadata:
  name: vault-ca
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to-matching: inject-vault-ca=true
  labels:
    argocd.argoproj.io/instance: vault-secret-testenvir
type: Opaque
data:
  ca.crt: LS0...LS0t
```

The target namespace:
```
apiVersion: v1
kind: Namespace
metadata:
  name: llopes
  labels:
    inject-vault-ca: "true"
```

**Expected behavior**
The namespaces labeled with the `inject-vault-ca: "true"` get installed/injected the `vault-ca`.

**Environment:**
 - Kubernetes version: [e.g. 1.28]
 - kubernetes-replicator version: [e.g. v2.10.0]

**Additional context**
```
time="2024-11-13T16:36:44Z" level=info msg="labels of namespace llopes changed, attempting to delete ConfigMaps that no longer match" kind=ConfigMap target=llopes
time="2024-11-13T16:36:44Z" level=info msg="labels of namespace llopes changed, attempting to replicate ConfigMaps" kind=ConfigMap target=llopes
time="2024-11-13T16:36:44Z" level=info msg="Replicated kubernetes-replicator/vault-ca to: llopes" source=kubernetes-replicator/vault-ca
```
