### ISSUE TITLE
Update Secret Key References when replicating secret

### ISSUE THREAD

**Issue by kachi-app** [mittwald/kubernetes-replicator#359]
**Is your feature request related to a problem? Please describe.**
I am using cert-manager to generate self signed certificate, then attached to bitnami mongodb Helm Charts. however cert-manager / bitnami mongodb doesn't allow to specify the tls key and crt. I am using this replicator to replicate my secrets, and I hope that replicator could have this feature.

https://artifacthub.io/packages/helm/bitnami/mongodb?modal=values&path=tls.caCert
https://cert-manager.io/docs/configuration/selfsigned/

**Describe the solution you'd like**
add a new annotations
```
annotations:
  replicator.v1.mittwald.de/secret-type-update: "Opaque"
  replicator.v1.mittwald.de/secret-key-update: |
    tls.key: example.key
    tls.crt: example.crt
```
if not specified, just keep as is
If not found, ignore
It could be multiline string, key=val separated by comma (,) or semi colon (;)

Results:
```
# From
type: kubernetes.io/tls
data:
  tls.crt: "xxxxx"
  tls.key: "aa"
# To
type: Opaque
data:
  example.key: "aa"
  example.crt: "xxxxx"
```
