### ISSUE TITLE
Prefixes and Suffixes

### ISSUE THREAD

**Issue by theanotherwise** [mittwald/kubernetes-replicator#381]
**Is your feature request related to a problem? Please describe.**
Prefixes and Suffixes

**Describe the solution you'd like**
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-name
  namespace: default
  annotations:
    replicator.v1.mittwald.de/replicate-to: my-namespace
    replicator.v1.mittwald.de/prefix: prefix
type: Opaque
data: {}
```

should create

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: prefix-secret-name
  namespace: my-namespace
type: Opaque
data: {}
```
