### ISSUE TITLE
Proposal: Configure replication with CR

### ISSUE THREAD

**Issue by martin-helmich** [mittwald/kubernetes-replicator#41]
**Acknowledgement**
This idea was originally presented by @HansK-p in #40.

**Issue**
Sometimes, deployment tools (or something as simple as `kubectl apply`) mess with already deployed (and replicated) secrets or config maps. This is especially the case for secrets of type other than `Opaque`: These have to be created with empty initial values (like `tls.crt=""` for secrets of type `kubernetes.io/tls`), which are then overridden by the replicator (and then overridden again by the next deployment). This is the main issue in #40, and also influential in #11, #23 and #28.

Another issue is that some source secrets are created automatically (by cert-manager, for example) without the option of adding custom annotations (also in #40).

**Proposed solution**
Introduce a new custom resource that describes secret (or configmap) replication, instead of using annotations:

```yaml
apiVersion: replicator.mittwald.systems/v1
kind: ReplicationConfig
metadata:
  name: target-secret
spec: # written by user
  source:
    namespace: some-namespace
    name: some-source-secret
    kind: Secret
status: # written by replicator
  phase: Replicated
  target:
    namespace: my-namespace
    name: target-secret
    kind: Secret
```

The replicator would observe these CRs and create the replicated secrets by itself. This would have the advantage that the replicated secrets themselves would be created and fully owned by the replicator itself (without any deployments tools messing with them). We could also ensure that they are created with the correct secret type to begin with.

**Roadmap**
To build this, we might want to consider migrating this controller to the Operator SDK. We would probably be able to port and mostly keep the main reconciliation loops as they are. Then, a new controller could be added to handle the `ReplicationConfig` CRs.
