### ISSUE TITLE
Replication of Roles and RoleBindings not working

### ISSUE THREAD

**Issue by roock** [mittwald/kubernetes-replicator#58]
**Describe the bug**
Configured a role and a role binding to replicate to a different name space using push method. The resources are not replicated to the destination name space. Logs are showing that the replication of the role and role binding are supposed to happen, but the resource do not show up on the destination name space. Replication of a secret works without issue.

**To Reproduce**

installation options used for kubernetes replicator:

```yaml
args:
  - -log-level=trace
  - -resync-period=1m
```

apply the following role and rolebinding to a namespace e.g. default

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  annotations:
    replicator.v1.mittwald.de/replicate-to: test1
  name: developers-role
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
      - "extensions"
    resources:
      - "configmaps"
      - "cronjobs"
      - "deployments"
      - "events"
      - "ingresses"
      - "jobs"
      - "pods"
      - "pods/attach"
      - "pods/exec"
      - "pods/log"
      - "pods/portforward"
      - "services"
    verbs:
      - "create"
      - "delete"
      - "describe"
      - "get"
      - "list"
      - "patch"
      - "update"
```

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    replicator.v1.mittwald.de/replicate-to: test1
  name: developer-RoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developers-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: developers
```

Log output: (with 
```
time="2020-10-23T09:20:01Z" level=info msg="Role default/developers-role to be replicated to: [test1]" kind=Role source=default/developers-role
time="2020-10-23T09:20:01Z" level=info msg="Checking if test1/developers-role exists? false" kind=Role source=default/developers-role target=test1/developers-role
time="2020-10-23T09:20:01Z" level=debug msg="Creating a new role test1/developers-role" kind=Role source=default/developers-role target=test1/developers-role
time="2020-10-23T09:20:01Z" level=info msg="RoleBinding default/developer-RoleBinding to be replicated to: [test1]" kind=RoleBinding source=default/developer-RoleBinding
time="2020-10-23T09:20:01Z" level=info msg="Checking if test1/developer-RoleBinding exists? false" kind=RoleBinding source=default/developer-RoleBinding target=test1/developer-RoleBinding
time="2020-10-23T09:20:01Z" level=debug msg="Creating a new roleBinding test1/developer-RoleBinding" kind=RoleBinding source=default/developer-RoleBinding target=test1/developer-RoleBinding
time="2020-10-23T09:20:01Z" level=info msg="Secret default/roock.test to be replicated to: [roock,r2-mono-230-review.*]" kind=Secret source=default/roock.test
time="2020-10-23T09:20:01Z" level=info msg="Checking if roock/roock.test exists? true" kind=Secret source=default/roock.test target=roock/roock.test
time="2020-10-23T09:20:01Z" level=debug msg="Secret roock/roock.test is already up-to-date" kind=Secret source=default/roock.test target=roock/roock.test
time="2020-10-23T09:21:01Z" level=info msg="Role default/developers-role to be replicated to: [test1]" kind=Role source=default/developers-role
time="2020-10-23T09:21:01Z" level=info msg="Checking if test1/developers-role exists? false" kind=Role source=default/developers-role target=test1/developers-role
time="2020-10-23T09:21:01Z" level=debug msg="Creating a new role test1/developers-role" kind=Role source=default/developers-role target=test1/developers-role
time="2020-10-23T09:21:01Z" level=info msg="RoleBinding default/developer-RoleBinding to be replicated to: [test1]" kind=RoleBinding source=default/developer-RoleBinding
time="2020-10-23T09:21:01Z" level=info msg="Checking if test1/developer-RoleBinding exists? false" kind=RoleBinding source=default/developer-RoleBinding target=test1/developer-RoleBinding
time="2020-10-23T09:21:01Z" level=debug msg="Creating a new roleBinding test1/developer-RoleBinding" kind=RoleBinding source=default/developer-RoleBinding target=test1/developer-RoleBinding
time="2020-10-23T09:21:01Z" level=info msg="Secret default/roock.test to be replicated to: [roock,r2-mono-230-review.*]" kind=Secret source=default/roock.test
time="2020-10-23T09:21:01Z" level=info msg="Checking if roock/roock.test exists? true" kind=Secret source=default/roock.test target=roock/roock.test
time="2020-10-23T09:21:01Z" level=debug msg="Secret roock/roock.test is already up-to-date" kind=Secret source=default/roock.test target=roock/roock.test
time="2020-10-23T09:22:01Z" level=info msg="Role default/developers-role to be replicated to: [test1]" kind=Role source=default/developers-role
time="2020-10-23T09:22:01Z" level=info msg="Checking if test1/developers-role exists? false" kind=Role source=default/developers-role target=test1/developers-role
time="2020-10-23T09:22:01Z" level=debug msg="Creating a new role test1/developers-role" kind=Role source=default/developers-role target=test1/developers-role
time="2020-10-23T09:22:01Z" level=info msg="RoleBinding default/developer-RoleBinding to be replicated to: [test1]" kind=RoleBinding source=default/developer-RoleBinding
time="2020-10-23T09:22:01Z" level=info msg="Checking if test1/developer-RoleBinding exists? false" kind=RoleBinding source=default/developer-RoleBinding target=test1/developer-RoleBinding
time="2020-10-23T09:22:01Z" level=debug msg="Creating a new roleBinding test1/developer-RoleBinding" kind=RoleBinding source=default/developer-RoleBinding target=test1/developer-RoleBinding
time="2020-10-23T09:22:01Z" level=info msg="Secret default/roock.test to be replicated to: [roock,r2-mono-230-review.*]" kind=Secret source=default/roock.test
time="2020-10-23T09:22:01Z" level=info msg="Checking if roock/roock.test exists? true" kind=Secret source=default/roock.test target=roock/roock.test
time="2020-10-23T09:22:01Z" level=debug msg="Secret roock/roock.test is already up-to-date" kind=Secret source=default/roock.test target=roock/roock.test
```

```shell
$ k create namespace test1
$ k -n test1 get role
No resources found.
$ k -n test1 get rolebinding
No resources found.
```

**Expected behavior**

developer and developer-RoleBinding should show up in test1 namespace.

**Environment:**
 - Kubernetes version: 1.15.10 and 1.18.9 (both minikube 1.12.3)
 - kubernetes-replicator version: 2.4.0
