### ISSUE TITLE
Allowing all namespaces.

### ISSUE THREAD

**Issue by linuxbsdfreak** [mittwald/kubernetes-replicator#7]
Hi,

What do i set in the annotation of the source secret  to allow the secret to be replicate it to all namespaces?

Regards,
Kevin

**Comment by martin-helmich** [comment]
The `replicator.v1.mittwald.de/replication-allowed-namespaces` annotation contains a regular expression. `.*` should match all namespaces.

```yaml
annotations:
  replicator.v1.mittwald.de/replication-allowed: "true"
  replicator.v1.mittwald.de/replication-allowed-namespaces: ".*"
```
