### ISSUE TITLE
Replicated keys do not get removed when source is deleted

### ISSUE THREAD

**Issue by YannikBramkamp** [mittwald/kubernetes-replicator#73]
**Describe the bug**
If a manually generated secret or resource receives keys via ```replicate-to```, the replicated keys are not removed upon deletion of the source secret.

**To Reproduce**
Manually generated resource:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-test
  namespace: test
  annotations:
data:
  test: "45"
```
Source resource:
```
aapiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-test
  annotations:
    replicator.v1.mittwald.de/replicate-to: "test"
data:
  test_data: "3"
```
Replication:
```
$ kubectl create namespace test
$ kubectl apply -f manual.yaml
$ kubectl apply -f source.yaml
$ kubectl delete configmap-test
$ kubectl get configmap configmap-test -n test -o yaml
apiVersion: v1
data:
  test: "45"
  test_data: "3"
```

**Expected behavior**
The key```test_data``` gets removed upon deletion of the source resource.

**Environment:**
 - Kubernetes version: [1.19]
 - kubernetes-replicator version: [v2.5.1]
