### ISSUE TITLE
Can not "replicate to" a secret which is "replicated from" another one.

### ISSUE THREAD

**Issue by eleblebici** [mittwald/kubernetes-replicator#86]
**Describe the bug**
I created a secret by using "pull-based replication" with the annotation "replicator.v1.mittwald.de/replicate-from:" and then annotated it with "replicator.v1.mittwald.de/replicate-to:" to replicate this secret to all namespaces. But it does not replicate this pulled secret to namespaces. When i try to replicate a not pulled secret (existing one) it is successfully pushing to all namespaces.

**To Reproduce**
Yaml file :

```
apiVersion: v1
kind: Secret
metadata:
  name: some-replicated-tls
  annotations:
    replicator.v1.mittwald.de/replicate-from: cert-manager/some-tls
    replicator.v1.mittwald.de/replicate-to: ''
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""
```

**Expected behavior**
Expect to push pulled secret to namespaces.

**Environment:**
 - Kubernetes version: [1.18.9]
 - kubernetes-replicator version: [v2.5.1]

**Additional context**
