### ISSUE TITLE
Secrets are not replicated when adding label to existing namespace

### ISSUE THREAD

**Issue by axdotl** [mittwald/kubernetes-replicator#93]
**Describe the bug**

When adding a label to an existing namespace, the desired secret is not replicated.

**To Reproduce**

- Running k8s cluster
- Create namespace `pizza`
- Deploy kubernetes-replicator
- Create k8s secret
  ```yaml
  apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      replicator.v1.mittwald.de/replicate-to-matching: |
        replicate-cheese-secret
    name: cheese
    namespace: default
  data:
    foo: bar
  type: Opaque
  ```
- Edit namespace `pizza` and set label `replicate-cheese-secret=1`
- Secret cheese will not replicated
- Restart kubernetes-replicator pod will trigger secret replication

**Expected behavior**

Set a label to an existing namespace should result in secret replication

**Environment:**
 - Kubernetes version: 1.17
 - kubernetes-replicator version: v2.5.1

**Additional context**

n/a
